[package]
name = "rtyping"
version = "1.0.13"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3

[dependencies]
rand = "0.8.5"
rodio = "0.20.1"
clap = "4.5.26"
ratatui = "0.29.0"
crossterm = { version = "0.28.1", features = ["event-stream"] }

[[bin]]
name = "rtyping"
path = "src/main.rs"
