[package]
name = "rtyping"
version = "1.0.17"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3

[dependencies]
rand = "0.9"
rodio = "0.21"
clap = "4"
ratatui = "0.30"
crossterm = { version = "0.29", features = ["event-stream"] }

[[bin]]
name = "rtyping"
path = "src/main.rs"
