[package]
name = "rtyping"
version = "1.0.14"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3

[dependencies]
rand = "0.8"
rodio = "0.20"
clap = "4"
ratatui = "0.29"
crossterm = { version = "0.28", features = ["event-stream"] }

[[bin]]
name = "rtyping"
path = "src/main.rs"
